In [ ]:
import os
from dotenv import load_dotenv
from typhoon_ocr import ocr_document
from bs4 import BeautifulSoup
import re
from rapidfuzz import fuzz

In [ ]:
markdown = ocr_document(
    pdf_or_image_path="../data/images/constituency_10_1_page2.png"
)

OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

In [ ]:
print(markdown)

ส.ส. ๖/๑

<table><tr><td>หมายเลข ประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัด พรรคการเมือง</td><td>ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>๕</td><td>นายปารเมศ วิทยารักษ์สรรค์</td><td>ประชาชน</td><td>๓๔,๑๖๗ (สามหมื่นสี่พันหนึ่งร้อยหกสิบเจ็ด)</td></tr><tr><td>๙</td><td>นายพีรวุฒิ พิมพ์สมฤดี</td><td>ประชาธิปัตย์</td><td>๑๔,๘๑๓ (หนึ่งหมื่นสี่พันแปดร้อยสิบสาม)</td></tr><tr><td>๑</td><td>นางสาวลลิดา เพรศิวัฒนา</td><td>ภูมิใจไทย</td><td>๑๔,๓๖๘ (หนึ่งหมื่นสี่พันสามร้อยหกสิบแปด)</td></tr><tr><td>๘</td><td>นายญาณกิตติ์ ห่วงทรัพย์</td><td>เพื่อไทย</td><td>๖,๐๓๐ (หกพันสามสิบ)</td></tr><tr><td>๖</td><td>นายพลัฏฐ์ ศิริกุลพิสุทธิ์</td><td>รวมไทยสร้างชาติ</td><td>๒,๐๗๕ (สองพันเจ็ดสิบห้า)</td></tr><tr><td>๑๒</td><td>นายแทนคุณ จิตอิสระ</td><td>โอกาสใหม่</td><td>๑,๑๓๓ (หนึ่งพันหนึ่งร้อยสามสิบสาม)</td></tr><tr><td>๗</td><td>นายภัทรพล หมดมลทิน</td><td>ไทยภักดี</td><td>๑,๐๒๓ (หนึ่งพันยี่สิบสาม)</td></tr><tr><td>๒</td><td>พันตำรวจโทหญิง แสนสุข อุทยานินทร์<

ส.ส. ๖/๑

<table><tr><td>หมายเลข ประจำตัว ผู้สมัคร</td><td>ชื่อตัว - ชื่อสกุล ผู้สมัครรับเลือกตั้ง</td><td>สังกัด พรรคการเมือง</td><td>ได้คะแนน (ให้กรอกทั้งตัวเลขและตัวอักษร)</td></tr><tr><td>๕</td><td>นายปารเมศ วิทยารักษ์สรรค์</td><td>ประชาชน</td><td>๓๔,๑๖๗ (สามหมื่นสี่พันหนึ่งร้อยหกสิบเจ็ด)</td></tr><tr><td>๙</td><td>นายพีรวุฒิ พิมพ์สมฤดี</td><td>ประชาธิปัตย์</td><td>๑๔,๘๑๓ (หนึ่งหมื่นสี่พันแปดร้อยสิบสาม)</td></tr><tr><td>๑</td><td>นางสาวลลิดา เพรศิวัฒนา</td><td>ภูมิใจไทย</td><td>๑๔,๓๖๘ (หนึ่งหมื่นสี่พันสามร้อยหกสิบแปด)</td></tr><tr><td>๘</td><td>นายญาณกิตติ์ ห่วงทรัพย์</td><td>เพื่อไทย</td><td>๖,๐๓๐ (หกพันสามสิบ)</td></tr><tr><td>๖</td><td>นายพลัฏฐ์ ศิริกุลพิสุทธิ์</td><td>รวมไทยสร้างชาติ</td><td>๒,๐๗๕ (สองพันเจ็ดสิบห้า)</td></tr><tr><td>๑๒</td><td>นายแทนคุณ จิตอิสระ</td><td>โอกาสใหม่</td><td>๑,๑๓๓ (หนึ่งพันหนึ่งร้อยสามสิบสาม)</td></tr><tr><td>๗</td><td>นายภัทรพล หมดมลทิน</td><td>ไทยภักดี</td><td>๑,๐๒๓ (หนึ่งพันยี่สิบสาม)</td></tr><tr><td>๒</td><td>พันตำรวจโทหญิง แสนสุข อุทยานินทร์</td><td>เศรษฐกิจ</td><td>๙๗๙ (เก้าร้อยเจ็ดสิบเก้า)</td></tr><tr><td>๑๑</td><td>นายพิเชษฐ์ ไทยนิยม</td><td>ไทยสร้างไทย</td><td>๖๒๙ (หนึ่งร้อยแปดสิบเก้า)</td></tr><tr><td>๑๖</td><td>นายกานต์ กิตติอำพน</td><td>ไทยก้าวใหม่</td><td>๔๘๙ (สี่ร้อยแปดสิบเก้า)</td></tr><tr><td>๔</td><td>นายธนะสิทธิ์ ล้อสุวรรณทีปต์</td><td>พลวัต</td><td>๓๕๑ (สามร้อยห้าสิบเอ็ด)</td></tr><tr><td>๓</td><td>นายอัครพล คฤหเดชรัตนา</td><td>กล้าธรรม</td><td>๒๔๔ (สองร้อยสี่สิบสี่)</td></tr><tr><td>๑๐</td><td>นายวีระยุทธ ประกอบการ</td><td>ปวงชนไทย</td><td>๑๖๘ (หนึ่งร้อยหกสิบแปด)</td></tr><tr><td>๑๕</td><td>นายอดัม ชินรัตนพิสิทธิ์</td><td>รักชาติ</td><td>๑๖๕ (หนึ่งร้อยห้าสิบสี่)</td></tr><tr><td>๑๗</td><td>นายประสงค์ ประสพโชค</td><td>ทางเลือกใหม่</td><td>๑๑๓ (หนึ่งร้อยสิบสาม)</td></tr><tr><td>๑๓</td><td>นายเลิศชาย สุจริตกุล</td><td>วิชชั่นใหม่</td><td>๑๕๔ (เก้าสิบสี่)</td></tr><tr><td>๑๔</td><td>นายมงคล เสมอภาพ</td><td>ประชาธิปไตยใหม่</td><td>๙๔ (แปดสิบ)</td></tr><tr><td>๑๘</td><td>นายกิตติคุณ ชื่นแย้ม</td><td>พลังประชารัฐ</td><td>๘๐ (แปดสิบ)</td></tr><tr><td colspan="3">รวมคะแนนทั้งสิ้น</td><td>๗๗,๐๗๕ (เจ็ดหมื่นเจ็ดพันเจ็ดสิบห้า)</td></tr></table>

In [ ]:
def thai_num_to_int(text: str) -> int:
    # Step 1: convert Thai digits to Arabic digits
    thai_to_arabic = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    text = text.translate(thai_to_arabic)

    # Step 2: extract leading number (digits + optional commas)
    match = re.match(r"[\d,]+", text)
    if not match:
        raise ValueError("No numeric value found")

    numeric_str = match.group().replace(",", "")

    # Step 3: convert to int
    return int(numeric_str)

In [ ]:
def extract_party_score_dict(html: str) -> dict:
    soup = BeautifulSoup(html, "html.parser")

    table = soup.find("table")
    if table is None:
        raise ValueError("No <table> found")

    rows = table.find_all("tr")
    if not rows:
        return {}

    # Extract header row
    headers = [td.get_text(strip=True) for td in rows[0].find_all(["td", "th"])]

    # Find best matching columns using Levenshtein-based similarity
    party_idx = None
    score_idx = None
    best_party_score = 0
    best_score_score = 0

    for i, h in enumerate(headers):
        party_sim = fuzz.partial_ratio(h, "ชื่อพรรคการเมือง")
        score_sim = fuzz.partial_ratio(h, "ได้คะแนน")

        if party_sim > best_party_score:
            best_party_score = party_sim
            party_idx = i

        if score_sim > best_score_score:
            best_score_score = score_sim
            score_idx = i

    # Optional: enforce threshold to avoid wrong matches
    if best_party_score < 60 or best_score_score < 60:
        raise ValueError("Required columns not confidently found")

    result = {}

    for row in rows[1:]:
        cols = [td.get_text(strip=True) for td in row.find_all("td")]

        if len(cols) <= max(party_idx, score_idx):
            continue

        key = cols[party_idx]
        value = cols[score_idx]

        try:
            value = thai_num_to_int(value)
        except ValueError:
            pass

        result[key] = value

    return result

In [ ]:
def extraction(path):
    try:
        markdown = ocr_document(
            pdf_or_image_path=path
        )
        party_dict = extract_party_score_dict(markdown)
        return party_dict
    except:
        return {}

In [ ]:
party = extraction("../data/images/party_list_34_11_page3.png")
party

{'ภูมิใจไทย': 16830,
 'พลังธรรมใหม่': 300,
 'กรีน': 58,
 'ไทยธรรม': 110,
 'แผ่นดินธรรม': 34,
 'กล้าธรรม': 157,
 'พลังประชารัฐ': 178,
 'โอกาสใหม่': 34,
 'เป็นธรรม': 70,
 'ประชาธิป': 17866,
 'ประชาไทย': 162,
 'ไทยสร้างไทย': 1146,
 'ไทยก้าวใหม่': 143,
 'ประชาอาสาชาติ': 64,
 'พร้อม': 43,
 'เครือข่ายชาวนาแห่งประเทศไทย': 20,
 'ไทยพิทักษ์ธรรม': 14,
 'ความหวังใหม่': 41,
 'เพื่อบ้านเมือง': 29,
 'พลังไทยรักชาติ': 43,
 'รวมคะแนนทั้งสิ้น': 78791}

In [ ]:
party = extraction("../data/images/party_list_34_11_page2.png")
party

{'มิติใหม่': 505,
 'รวมใจไทย': 981,
 'รวมไทยสร้างชาติ': 1680,
 'พลวัต': 294,
 'ประชาธิปไตยใหม่': 558,
 'เพื่อไทย': 13111,
 'ทางเลือกใหม่': 394,
 'เศรษฐกิจ': 4913,
 'เสรีรวมไทย': 569,
 'รวมพลังประชาชน': 506,
 'ท้องที่ไทย': 72,
 'อนาคตไทย': 85,
 'พลังเพื่อไทย': 272,
 'ไทยชนะ': 185,
 'พลังสังคมใหม่': 30,
 'สังคมประชาธิปไตยไทย': 54,
 'พิวซัน': 63,
 'ไทรวมพลัง': 6554,
 'ก้าวอิสระ': 71,
 'ปวงชนไทย': 115,
 'วิชชั่นใหม่': 317,
 'เพื่อชีวิตใหม่': 57,
 'คลองไทย': 120,
 'ประชาธิปัตย์': 2921,
 'ไทยก้าวหน้า': 171,
 'ไทยภักดี': 307,
 'แรงงานสร้างชาติ': 134,
 'ประชากรไทย': 255,
 'ครูไทยเพื่อประชาชน': 202,
 'ประชาชาติ': 151,
 'สร้างอนาคตไทย': 142,
 'รักชาติ': 204,
 'ไทยพร้อม': ''}

In [ ]:
party = extraction("../image.png")
party

{'ไทยธรรม': 90,
 'แผนกธรรม': 33,
 'กล้าธรรม': 171,
 'พลังประชารัฐ': 197,
 'โอกาสใหม่': 1239,
 'เป็นธรรม': 73,
 'ประชาธน': 26222,
 'ประชาไทย': 239,
 'ไทยสร้างไทย': 305,
 'ไทยก้าวใหม่': 193,
 'ประชาอาสาชาติ': 14,
 'พร้อม': 71}

In [ ]:
page1 = extraction("../data/images/constituency_18_2.png")
page2 = extraction("../data/images/constituency_18_2_page2.png")
page3 = extraction("../data/images/constituency_18_2_page3.png")

In [ ]:
print(page1)
print(page2)
print(page3)

{}
{'ภูมิใจไทย': 54585, 'ประชาชน': 16933, 'เพื่อไทย': 8937, 'ประชาธิปัตย์': 2819, 'พลังประชารัฐ': 747, 'กล้าธรรม': 463}
{}
