[project]
name = "superai-ss6-minihack2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "cuda-bindings>=13.2.0",
    "cv>=1.0.0",
    "nvidia-cuda-cupti-cu12>=12.9.79",
    "nvidia-cudnn-cu12>=9.20.0.48",
    "nvidia-cusparse-cu12>=12.5.10.65",
    "nvidia-nccl-cu12>=2.29.7",
    "nvidia-nvjitlink-cu12>=12.9.86",
    "openai>=2.29.0",
    "opencv-python-headless>=4.13.0.92",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.2",
    "rapidfuzz>=3.14.3",
    "triton>=3.6.0",
    "typhoon-ocr>=0.4.1",
]
